/*
 data format

 {
    avatar:"https://ik.imagekit.io/kyc/team/Santosh_Pashvan_Physical_Trainer.jpeg",
    name: "Santosh Paswan",
    title: "Physical Trainer",
    facebook: "",
    instagram: "",
    linkedin: "",
    twitter: "",
  },
*/
export const TeamData = [
{
    avatar:"https://ik.imagekit.io/kyc/team/Pankaj_Jha_President.jpeg",
    name: "Pankaj Jha",
    title: "President",
    facebook: "",
    instagram: "",
    linkedin: "",
    twitter: "",
  },
  {
    avatar:"https://ik.imagekit.io/kyc/team/Dr_P_R_Sultaniya_Promoter.jpeg",
    name: "Dr P R Sultania",
    title: "Promoter",
    facebook: "",
    instagram: "",
    linkedin: "",
    twitter: "",
  },
  {
    avatar:"https://ik.imagekit.io/kyc/team/Dr_Aneeta_Jha_Promoter.jpeg",
    name: "Dr Anita Jha",
    title: "Promoter",
    facebook: "",
    instagram: "",
    linkedin: "",
    twitter: "",
  },
 {
    avatar:"https://ik.imagekit.io/kyc/team/Santosh_Pashvan_Physical_Trainer.jpeg",
    name: "Santosh Paswan",
    title: "Physical Trainer",
    facebook: "",
    instagram: "",
    linkedin: "",
    twitter: "",
  },
  {
    avatar:"https://ik.imagekit.io/kyc/team/Dileep_Kumar_Jha_Member.jpeg",
    name: "Dileep Kumar Jha",
    title: "Member",
    facebook: "",
    instagram: "",
    linkedin: "",
    twitter: "",
  },
  {
    avatar:"https://ik.imagekit.io/kyc/team/Ashok_Kumar_Jgha_NSG_Commando.jpeg",
    name: "Ashok Kumar Jha",
    title: "NSG Commando",
    facebook: "",
    instagram: "",
    linkedin: "",
    twitter: "",
  },
 {
    avatar:"https://ik.imagekit.io/kyc/team/komal_singh_delhi_member.jpeg",
    name: "Komal Singh",
    title: "Delhi Team Member",
    facebook: "",
    instagram: "",
    linkedin: "",
    twitter: "",
  },
   {
    avatar:"https://ik.imagekit.io/kyc/team/Pradeep_Jha_Member.jpeg",
    name: "Pradeep Jha",
    title: "Member",
    facebook: "",
    instagram: "",
    linkedin: "",
    twitter: "",
  },
   
   {
    avatar:"https://ik.imagekit.io/kyc/team/Yogesh_Sahravat_Member.jpeg",
    name: "Yogesh Sahravat",
    title: "Member",
    facebook: "",
    instagram: "",
    linkedin: "",
    twitter: "",
  },
 {
    avatar:"https://ik.imagekit.io/kyc/team/Manish_Kumar_Jha_Member.jpeg",
    name: "Manish Kumar Jha",
    title: "Member",
    facebook: "",
    instagram: "",
    linkedin: "",
    twitter: "",
  },
 
 {
    avatar:"https://ik.imagekit.io/kyc/team/santosh_jha_member.jpeg",
    name: "Santosh Jha",
    title: "Member",
    facebook: "",
    instagram: "",
    linkedin: "",
    twitter: "",
  },
 {
    avatar:"https://ik.imagekit.io/kyc/team/Laxman_Pandit_Member.jpeg",
    name: "Laxman Pandit",
    title: "Member",
    facebook: "",
    instagram: "",
    linkedin: "",
    twitter: "",
  }
];
