export const SliderData = [
  {
    image:
      "https://ik.imagekit.io/kyc/carousel/1.jpeg",
  },
  {
    image:
      "https://ik.imagekit.io/kyc/carousel/2.jpeg",
  },
  {
    image:
      "https://ik.imagekit.io/kyc/carousel/3.jpeg",
  },
  {
    image:
      "https://ik.imagekit.io/kyc/carousel/4.jpeg",
  },
  {
    image:
      "https://ik.imagekit.io/kyc/carousel/5.jpeg",
  },
  {
    image:
      "https://ik.imagekit.io/kyc/carousel/6.jpeg",
  },
  {
    image:
      "https://ik.imagekit.io/kyc/carousel/7.jpeg",
  }
];
